import { readFileSync } from "node:fs";
const raw = JSON.parse(readFileSync(process.argv[2], "utf8"));
const d = raw.data ?? raw;
console.log("applicable:", d.applicable);
console.log("objectives:");
for (const o of d.request.objectives) console.log("  ", o.key, "|", o.dir, "|", o.unit ?? "(无单位)", "|", o.label);
console.log("unavailable:");
for (const g of d.request.unavailableObjectives) console.log("  ", g.key, "::", g.reason);
const o = d.request.args.orders;
console.log("orders:", o.length, "| penalty 非零行数:", o.filter((x) => x.penalty > 0).length);
console.log("note:", d.note);
