import { existsSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire("/home/user/complete/apps/frontend-shell/package.json");
const exe = ["/opt/pw-browsers/chromium-1194/chrome-linux/chrome"].find(existsSync);
const { chromium } = require("playwright-core");
const SP = "/tmp/claude-0/-home-user-complete/3f5e96d7-59cd-5a3f-aa1a-9551fc6f8f15/scratchpad";
const b = await chromium.launch({ executablePath: exe, args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const page = await b.newPage({ viewport: { width: 1440, height: 1200 } });
await page.goto("http://127.0.0.1:5221/", { waitUntil: "networkidle" });
await page.fill("#login-username", "admin");
await page.fill("#login-password", "demo1234");
await page.click("button[type=submit]");
await page.waitForTimeout(2500);
await page.evaluate(() => { window.history.pushState({}, "", "/admin/tickets"); window.dispatchEvent(new PopStateEvent("popstate")); });
await page.waitForSelector("[data-testid^=tc-row-]", { timeout: 12000 });
await page.locator("[data-testid^=tc-row-]").first().click();
await page.waitForSelector("[data-testid=tc-db-approvals]", { timeout: 8000 });
const cnt = await page.locator("[data-testid=tc-db-approval-count]").textContent();
const sectionText = await page.locator("[data-testid=tc-db-approvals]").innerText();
const ids = await page.locator("[data-testid^=tc-db-approval-act_]").evaluateAll((els) => els.map((e) => e.getAttribute("data-testid")));
console.log("SECTION count badge:", cnt);
console.log("SECTION rows (testids):", JSON.stringify(ids));
console.log("SECTION innerText:\n" + sectionText);
await page.screenshot({ path: `${SP}/rv-on-section-visible.png`, fullPage: true }).catch(() => {});
// also crop the drawer for a focused shot
const drawer = page.locator("[data-testid=tc-drawer]");
await drawer.screenshot({ path: `${SP}/rv-on-drawer.png` }).catch(() => {});
await b.close();
console.log("captured");
