import { existsSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire("/home/user/complete/apps/frontend-shell/package.json");
const exe = ["/opt/pw-browsers/chromium-1194/chrome-linux/chrome"].find(existsSync);
const { chromium } = require("playwright-core");
const SP = "/tmp/claude-0/-home-user-complete/3f5e96d7-59cd-5a3f-aa1a-9551fc6f8f15/scratchpad";
const b = await chromium.launch({ executablePath: exe, args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const page = await b.newPage({ viewport: { width: 1440, height: 1400 } });
await page.goto("http://127.0.0.1:5221/", { waitUntil: "networkidle" });
await page.fill("#login-username", "admin"); await page.fill("#login-password", "demo1234");
await page.click("button[type=submit]"); await page.waitForTimeout(2500);
await page.evaluate(() => { window.history.pushState({}, "", "/admin/data-builder"); window.dispatchEvent(new PopStateEvent("popstate")); });
await page.waitForTimeout(3500);
const url = await page.evaluate(() => window.location.pathname);
const oldCount = await page.locator("[data-testid=db-approval-count]").count();
const oldCountTxt = oldCount ? await page.locator("[data-testid=db-approval-count]").textContent() : "N/A";
const oldApproveBtns = await page.locator("[data-testid^=db-approve-]").count();
console.log("URL:", url);
console.log("OLD DataBuilder InPlaceApprovalPanel present:", oldCount > 0, "count badge:", oldCountTxt, "approve buttons:", oldApproveBtns);
await page.screenshot({ path: `${SP}/rv-oldface.png`, fullPage: false }).catch(()=>{});
await b.close();
