import pw from "/home/user/complete/node_modules/playwright-core/index.js";
const { chromium } = pw;
const SHOT = "/tmp/claude-0/-home-user-complete/3f5e96d7-59cd-5a3f-aa1a-9551fc6f8f15/scratchpad";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", headless: true, args: ["--no-sandbox"] });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
page.on("console", (m) => console.log("CONSOLE", m.type(), m.text().slice(0,200)));
page.on("response", (r) => { const u=r.url(); if(u.includes("/a/v1/")||u.includes("/b/v1/")||u.includes("/api/v1/")) console.log("NET", r.status(), u.replace("http://127.0.0.1:4001","DC").replace("http://127.0.0.1:4102","AC")); });
page.on("requestfailed", (r) => console.log("REQFAIL", r.url(), r.failure()?.errorText));
await page.goto("http://127.0.0.1:5201", { waitUntil: "networkidle" });
console.log("URL after goto:", page.url());
console.log("has #login-username:", !!(await page.$("#login-username")));
await page.fill("#login-tenant", "demo");
await page.fill("#login-username", "admin");
await page.fill("#login-password", "demo1234");
await page.click('button[type="submit"]');
await sleep(5000);
console.log("URL after login:", page.url());
await page.screenshot({ path: `${SHOT}/pw-debug-afterlogin.png`, fullPage: true });
const bodyText = (await page.evaluate(() => document.body.innerText)).slice(0, 500);
console.log("BODY TEXT:", bodyText.replace(/\n+/g," | "));
console.log("inputs on page:", await page.evaluate(() => [...document.querySelectorAll("input")].map(i=>i.getAttribute("aria-label")||i.id||i.type)));
console.log("testids:", await page.evaluate(() => [...document.querySelectorAll("[data-testid]")].map(e=>e.getAttribute("data-testid")).slice(0,30)));
await browser.close();
