import pw from "/home/user/complete/node_modules/playwright-core/index.js";
const { chromium } = pw;
const EXE = "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const APP = "http://127.0.0.1:5173";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch({ executablePath: EXE, args: ["--no-sandbox"] });
const page = await (await browser.newContext({ viewport: { width: 1600, height: 1100 } })).newPage();
let fullBody = null, fullResp = null, status = null, reqHeaders = null;
page.on("request", (r) => { if (r.url().includes("/b/v1/queries") && r.method() === "POST") { fullBody = r.postData(); reqHeaders = r.headers(); } });
page.on("response", async (r) => { if (r.url().includes("/b/v1/queries") && r.request().method() === "POST" && !r.url().includes("/events")) { status = r.status(); try { fullResp = await r.text(); } catch {} } });
await page.goto(`${APP}/login`, { waitUntil: "networkidle" });
await page.fill("#login-tenant", "demo"); await page.fill("#login-username", "admin"); await page.fill("#login-password", "demo1234");
await page.click('button[type="submit"]');
await page.waitForURL((u) => !u.pathname.includes("/login"), { timeout: 15000 }); await sleep(1500);
await page.evaluate(() => { window.history.pushState({}, "", "/admin/modeling"); window.dispatchEvent(new PopStateEvent("popstate")); });
await sleep(3500);
await page.locator('[data-testid="modeling-agent-input"]').fill("现金垫45亿过得了体检吗？");
await page.locator('[data-testid="modeling-agent-send"]').click();
await sleep(2500);
console.log("=== 浏览器完整 POST body ===");
console.log(fullBody);
console.log("=== 关键请求头 ===");
console.log("  Idempotency-Key:", reqHeaders?.["idempotency-key"], "| Authorization:", (reqHeaders?.["authorization"] || "").slice(0, 25) + "…");
console.log("=== POST 响应 HTTP", status, "===");
console.log(fullResp);
await browser.close();
