const A="http://127.0.0.1:8081", B="http://127.0.0.1:8082";
const j=(r)=>r.json();
const login=async(u,p)=>(await fetch(A+"/a/v1/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:u,password:p})}).then(j)).token;
const ask=async(t,q,view,sel=[])=>{const r=await fetch(B+"/b/v1/queries",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+t},body:JSON.stringify({query:q,context:{view,selectedObjects:sel,filters:{}}})}).then(j);await new Promise(s=>setTimeout(s,1200));return fetch(B+"/b/v1/queries/"+r.taskId,{headers:{authorization:"Bearer "+t}}).then(j)};
const assert=(c,m)=>{if(!c){console.error("✗ "+m);process.exit(1)}console.log("✓ "+m)};
const t=await login("planner","planner123");
let r=await ask(t,"4680-NCM 加 20% 六周能不能接？","dash");
assert(r.path==="WORKFLOW"&&r.answer?.blocks.some(b=>b.type==="kpi")&&!r.answer.unverifiedNumerics,"路径A 产能预测+溯源");
r=await ask(t,"4680-NCM 加 60% 六周能不能接？","dash");
assert(r.answer?.blocks[0]?.type==="rule_violation"&&r.answer.blocks[0].ruleId==="C03","C03 阻断");
r=await ask(t,"影响哪些订单？","risk",[{objectType:"Base",objectId:"b-cz",label:"常州基地·总部"}]);
assert(r.slots?.baseName==="常州基地·总部","上下文槽位补全");
r=await ask(t,"对比储能和动力基地利用率","explore");
assert(r.path==="AGENT"&&r.answer?.trustLevel==="AGENT_EXPLORATORY","路径B Agent");
r=await ask(t,"今天天气如何","audit");
assert(r.answer?.blocks[0]?.markdown.includes("换个问法"),"WORKFLOW_ONLY 拒绝");
const cz=await login("czmgr","cz123");
const bases=await fetch(A+"/a/v1/objects/query",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+cz},body:JSON.stringify({objectType:"Base"})}).then(j);
assert(bases.data.length===1&&bases.data[0].name==="常州基地·总部","行级权限");
r=await ask(t,"采纳常州的三班制方案","risk");
assert(r.answer?.blocks[0]?.type==="action_draft","Action 草稿");
console.log("\n全部冒烟通过 ✅");
